# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bpfeat.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_bpui(object):
    def setupUi(self, bpui):
        bpui.setObjectName(_fromUtf8("bpui"))
        bpui.resize(1310, 893)
        self.centralwidget = QtGui.QWidget(bpui)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_41 = QtGui.QVBoxLayout()
        self.verticalLayout_41.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_41.setSpacing(0)
        self.verticalLayout_41.setObjectName(_fromUtf8("verticalLayout_41"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(550, 16777215))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.uicd = QtGui.QPushButton(self.tab_3)
        self.uicd.setObjectName(_fromUtf8("uicd"))
        self.horizontalLayout_11.addWidget(self.uicd)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_11.addLayout(self.horizontalLayout_12)
        self.treeFiles = QtGui.QTreeView(self.tab_3)
        self.treeFiles.setObjectName(_fromUtf8("treeFiles"))
        self.verticalLayout_11.addWidget(self.treeFiles)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout_11.addLayout(self.horizontalLayout_13)
        self.widget = QtGui.QWidget(self.tab_3)
        self.widget.setMinimumSize(QtCore.QSize(0, 200))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.sfW = QtGui.QWidget(self.widget)
        self.sfW.setObjectName(_fromUtf8("sfW"))
        self.verticalLayout_28 = QtGui.QVBoxLayout(self.sfW)
        self.verticalLayout_28.setObjectName(_fromUtf8("verticalLayout_28"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_13 = QtGui.QLabel(self.sfW)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_15.addWidget(self.label_13)
        self.selectSf = QtGui.QDoubleSpinBox(self.sfW)
        self.selectSf.setMaximum(500000.0)
        self.selectSf.setProperty("value", 0.0)
        self.selectSf.setObjectName(_fromUtf8("selectSf"))
        self.horizontalLayout_15.addWidget(self.selectSf)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem2)
        self.verticalLayout_28.addLayout(self.horizontalLayout_15)
        self.verticalLayout_12.addWidget(self.sfW)
        self.dataVarW = QtGui.QWidget(self.widget)
        self.dataVarW.setObjectName(_fromUtf8("dataVarW"))
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.dataVarW)
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_28 = QtGui.QLabel(self.dataVarW)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_14.addWidget(self.label_28)
        self.selectData = QtGui.QComboBox(self.dataVarW)
        self.selectData.setObjectName(_fromUtf8("selectData"))
        self.horizontalLayout_14.addWidget(self.selectData)
        self.dataShape = QtGui.QLabel(self.dataVarW)
        self.dataShape.setText(_fromUtf8(""))
        self.dataShape.setObjectName(_fromUtf8("dataShape"))
        self.horizontalLayout_14.addWidget(self.dataShape)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem3)
        self.verticalLayout_23.addLayout(self.horizontalLayout_14)
        self.verticalLayout_12.addWidget(self.dataVarW)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem4)
        self.datasetValid = QtGui.QLabel(self.widget)
        self.datasetValid.setText(_fromUtf8(""))
        self.datasetValid.setObjectName(_fromUtf8("datasetValid"))
        self.horizontalLayout_18.addWidget(self.datasetValid)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem5)
        self.verticalLayout_12.addLayout(self.horizontalLayout_18)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.verticalLayout_11.addWidget(self.widget)
        self.verticalLayout_4.addLayout(self.verticalLayout_11)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.label_7 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setOpenExternalLinks(True)
        self.label_7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem6)
        self.label_23 = QtGui.QLabel(self.tab_4)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_20.addWidget(self.label_23)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem7)
        self.verticalLayout_17.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem8)
        self.rawPanelBox = QtGui.QRadioButton(self.tab_4)
        self.rawPanelBox.setChecked(True)
        self.rawPanelBox.setObjectName(_fromUtf8("rawPanelBox"))
        self.horizontalLayout_27.addWidget(self.rawPanelBox)
        self.erpPanelBox = QtGui.QRadioButton(self.tab_4)
        self.erpPanelBox.setObjectName(_fromUtf8("erpPanelBox"))
        self.horizontalLayout_27.addWidget(self.erpPanelBox)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem9)
        self.verticalLayout_17.addLayout(self.horizontalLayout_27)
        self.rawPanel = QtGui.QWidget(self.tab_4)
        self.rawPanel.setMinimumSize(QtCore.QSize(0, 0))
        self.rawPanel.setObjectName(_fromUtf8("rawPanel"))
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.rawPanel)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.rawAcross = QtGui.QRadioButton(self.rawPanel)
        self.rawAcross.setChecked(True)
        self.rawAcross.setObjectName(_fromUtf8("rawAcross"))
        self.horizontalLayout_16.addWidget(self.rawAcross)
        self.rawPer = QtGui.QRadioButton(self.rawPanel)
        self.rawPer.setObjectName(_fromUtf8("rawPer"))
        self.horizontalLayout_16.addWidget(self.rawPer)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.rawChanW = QtGui.QWidget(self.rawPanel)
        self.rawChanW.setObjectName(_fromUtf8("rawChanW"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.rawChanW)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem10)
        self.label_19 = QtGui.QLabel(self.rawChanW)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_23.addWidget(self.label_19)
        self.rawChan = QtGui.QSpinBox(self.rawChanW)
        self.rawChan.setObjectName(_fromUtf8("rawChan"))
        self.horizontalLayout_23.addWidget(self.rawChan)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem11)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_23)
        self.verticalLayout_10.addWidget(self.rawChanW)
        self.verticalLayout_21.addLayout(self.verticalLayout_10)
        self.verticalLayout_17.addWidget(self.rawPanel)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.verticalLayout_17.addLayout(self.horizontalLayout_28)
        self.erpPanel = QtGui.QWidget(self.tab_4)
        self.erpPanel.setMinimumSize(QtCore.QSize(0, 0))
        self.erpPanel.setObjectName(_fromUtf8("erpPanel"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.erpPanel)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.erpAcross = QtGui.QRadioButton(self.erpPanel)
        self.erpAcross.setChecked(True)
        self.erpAcross.setObjectName(_fromUtf8("erpAcross"))
        self.horizontalLayout_21.addWidget(self.erpAcross)
        self.erpPer = QtGui.QRadioButton(self.erpPanel)
        self.erpPer.setObjectName(_fromUtf8("erpPer"))
        self.horizontalLayout_21.addWidget(self.erpPer)
        self.verticalLayout_15.addLayout(self.horizontalLayout_21)
        self.widget_2 = QtGui.QWidget(self.erpPanel)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.erpSTD = QtGui.QRadioButton(self.widget_2)
        self.erpSTD.setChecked(False)
        self.erpSTD.setObjectName(_fromUtf8("erpSTD"))
        self.horizontalLayout_26.addWidget(self.erpSTD)
        self.erpSEM = QtGui.QRadioButton(self.widget_2)
        self.erpSEM.setChecked(True)
        self.erpSEM.setObjectName(_fromUtf8("erpSEM"))
        self.horizontalLayout_26.addWidget(self.erpSEM)
        self.verticalLayout_20.addLayout(self.horizontalLayout_26)
        self.verticalLayout_15.addWidget(self.widget_2)
        self.erpChanW = QtGui.QWidget(self.erpPanel)
        self.erpChanW.setObjectName(_fromUtf8("erpChanW"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.erpChanW)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem12)
        self.label_20 = QtGui.QLabel(self.erpChanW)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_25.addWidget(self.label_20)
        self.erpChan = QtGui.QSpinBox(self.erpChanW)
        self.erpChan.setObjectName(_fromUtf8("erpChan"))
        self.horizontalLayout_25.addWidget(self.erpChan)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem13)
        self.verticalLayout_19.addLayout(self.horizontalLayout_25)
        self.verticalLayout_15.addWidget(self.erpChanW)
        self.verticalLayout_14.addLayout(self.verticalLayout_15)
        self.verticalLayout_17.addWidget(self.erpPanel)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem14)
        self.verticalLayout_18.addLayout(self.verticalLayout_17)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem15)
        self.label_15 = QtGui.QLabel(self.tab_5)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_7.addWidget(self.label_15)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem16)
        self.verticalLayout_16.addLayout(self.horizontalLayout_7)
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_5)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem17)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem18)
        self.powTable = QtGui.QTableWidget(self.groupBox_3)
        self.powTable.setMinimumSize(QtCore.QSize(400, 0))
        self.powTable.setObjectName(_fromUtf8("powTable"))
        self.powTable.setColumnCount(3)
        self.powTable.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.powTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(5, 2, item)
        self.horizontalLayout_4.addWidget(self.powTable)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem19)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem20)
        self.powFceAdd = QtGui.QPushButton(self.groupBox_3)
        self.powFceAdd.setObjectName(_fromUtf8("powFceAdd"))
        self.horizontalLayout.addWidget(self.powFceAdd)
        self.powFceRm = QtGui.QPushButton(self.groupBox_3)
        self.powFceRm.setObjectName(_fromUtf8("powFceRm"))
        self.horizontalLayout.addWidget(self.powFceRm)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem21)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_34 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_34.setObjectName(_fromUtf8("verticalLayout_34"))
        self.horizontalLayout_41 = QtGui.QHBoxLayout()
        self.horizontalLayout_41.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_41.setObjectName(_fromUtf8("horizontalLayout_41"))
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_41.addItem(spacerItem22)
        self.powAllChan = QtGui.QRadioButton(self.groupBox_5)
        self.powAllChan.setChecked(True)
        self.powAllChan.setObjectName(_fromUtf8("powAllChan"))
        self.horizontalLayout_41.addWidget(self.powAllChan)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_41.addItem(spacerItem23)
        self.powSelectChan = QtGui.QRadioButton(self.groupBox_5)
        self.powSelectChan.setObjectName(_fromUtf8("powSelectChan"))
        self.horizontalLayout_41.addWidget(self.powSelectChan)
        self.powChanNb = QtGui.QSpinBox(self.groupBox_5)
        self.powChanNb.setObjectName(_fromUtf8("powChanNb"))
        self.horizontalLayout_41.addWidget(self.powChanNb)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_41.addItem(spacerItem24)
        self.verticalLayout_34.addLayout(self.horizontalLayout_41)
        self.verticalLayout.addWidget(self.groupBox_5)
        spacerItem25 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem25)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem26)
        self.powFceUp = QtGui.QPushButton(self.tab)
        self.powFceUp.setObjectName(_fromUtf8("powFceUp"))
        self.horizontalLayout_10.addWidget(self.powFceUp)
        self.powRun = QtGui.QPushButton(self.tab)
        self.powRun.setObjectName(_fromUtf8("powRun"))
        self.horizontalLayout_10.addWidget(self.powRun)
        self.powLoad = QtGui.QPushButton(self.tab)
        self.powLoad.setObjectName(_fromUtf8("powLoad"))
        self.horizontalLayout_10.addWidget(self.powLoad)
        self.powSave = QtGui.QPushButton(self.tab)
        self.powSave.setObjectName(_fromUtf8("powSave"))
        self.horizontalLayout_10.addWidget(self.powSave)
        spacerItem27 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem27)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, 10, -1, 10)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_11 = QtGui.QLabel(self.tab_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_19.addWidget(self.label_11)
        self.powFce2Plt = QtGui.QComboBox(self.tab_2)
        self.powFce2Plt.setObjectName(_fromUtf8("powFce2Plt"))
        self.horizontalLayout_19.addWidget(self.powFce2Plt)
        spacerItem28 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem28)
        self.verticalLayout_5.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        spacerItem29 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem29)
        self.powAcross = QtGui.QRadioButton(self.tab_2)
        self.powAcross.setObjectName(_fromUtf8("powAcross"))
        self.horizontalLayout_22.addWidget(self.powAcross)
        self.powPer1D = QtGui.QRadioButton(self.tab_2)
        self.powPer1D.setChecked(True)
        self.powPer1D.setObjectName(_fromUtf8("powPer1D"))
        self.horizontalLayout_22.addWidget(self.powPer1D)
        self.powPer2D = QtGui.QRadioButton(self.tab_2)
        self.powPer2D.setObjectName(_fromUtf8("powPer2D"))
        self.horizontalLayout_22.addWidget(self.powPer2D)
        self.powTopo = QtGui.QRadioButton(self.tab_2)
        self.powTopo.setObjectName(_fromUtf8("powTopo"))
        self.horizontalLayout_22.addWidget(self.powTopo)
        spacerItem30 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem30)
        self.verticalLayout_5.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        spacerItem31 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem31)
        self.label_22 = QtGui.QLabel(self.tab_2)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_30.addWidget(self.label_22)
        self.powChan = QtGui.QSpinBox(self.tab_2)
        self.powChan.setObjectName(_fromUtf8("powChan"))
        self.horizontalLayout_30.addWidget(self.powChan)
        spacerItem32 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem32)
        self.verticalLayout_5.addLayout(self.horizontalLayout_30)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        spacerItem33 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem33)
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.verticalLayout_37 = QtGui.QVBoxLayout(self.tab_11)
        self.verticalLayout_37.setObjectName(_fromUtf8("verticalLayout_37"))
        self.verticalLayout_36 = QtGui.QVBoxLayout()
        self.verticalLayout_36.setObjectName(_fromUtf8("verticalLayout_36"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem34 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem34)
        self.advResume = QtGui.QLabel(self.tab_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.advResume.setFont(font)
        self.advResume.setText(_fromUtf8(""))
        self.advResume.setObjectName(_fromUtf8("advResume"))
        self.horizontalLayout_6.addWidget(self.advResume)
        spacerItem35 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem35)
        self.verticalLayout_36.addLayout(self.horizontalLayout_6)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_11)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.powBsl = QtGui.QCheckBox(self.groupBox_4)
        self.powBsl.setObjectName(_fromUtf8("powBsl"))
        self.horizontalLayout_17.addWidget(self.powBsl)
        self.powBslW = QtGui.QWidget(self.groupBox_4)
        self.powBslW.setObjectName(_fromUtf8("powBslW"))
        self.horizontalLayout_42 = QtGui.QHBoxLayout(self.powBslW)
        self.horizontalLayout_42.setObjectName(_fromUtf8("horizontalLayout_42"))
        self.label_8 = QtGui.QLabel(self.powBslW)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_42.addWidget(self.label_8)
        self.powBslFrom = QtGui.QSpinBox(self.powBslW)
        self.powBslFrom.setMaximum(16777215)
        self.powBslFrom.setObjectName(_fromUtf8("powBslFrom"))
        self.horizontalLayout_42.addWidget(self.powBslFrom)
        self.label_9 = QtGui.QLabel(self.powBslW)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_42.addWidget(self.label_9)
        self.powBslTo = QtGui.QSpinBox(self.powBslW)
        self.powBslTo.setMaximum(16777215)
        self.powBslTo.setObjectName(_fromUtf8("powBslTo"))
        self.horizontalLayout_42.addWidget(self.powBslTo)
        self.label_10 = QtGui.QLabel(self.powBslW)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_42.addWidget(self.label_10)
        self.powNorm = QtGui.QSpinBox(self.powBslW)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.powNorm.setFont(font)
        self.powNorm.setMaximum(4)
        self.powNorm.setProperty("value", 0)
        self.powNorm.setObjectName(_fromUtf8("powNorm"))
        self.horizontalLayout_42.addWidget(self.powNorm)
        self.horizontalLayout_17.addWidget(self.powBslW)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.verticalLayout_36.addWidget(self.groupBox_4)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_11)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_35 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_35.setObjectName(_fromUtf8("verticalLayout_35"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem36 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem36, 2, 9, 1, 1)
        self.powCycle = QtGui.QSpinBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.powCycle.setFont(font)
        self.powCycle.setMinimum(1)
        self.powCycle.setMaximum(20)
        self.powCycle.setProperty("value", 3)
        self.powCycle.setObjectName(_fromUtf8("powCycle"))
        self.gridLayout.addWidget(self.powCycle, 2, 7, 1, 1)
        self.powDetrend = QtGui.QCheckBox(self.groupBox_6)
        self.powDetrend.setText(_fromUtf8(""))
        self.powDetrend.setObjectName(_fromUtf8("powDetrend"))
        self.gridLayout.addWidget(self.powDetrend, 5, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.powWidthW = QtGui.QSpinBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.powWidthW.setFont(font)
        self.powWidthW.setMinimum(1)
        self.powWidthW.setProperty("value", 7)
        self.powWidthW.setObjectName(_fromUtf8("powWidthW"))
        self.gridLayout.addWidget(self.powWidthW, 4, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 3, 1, 1)
        self.powBut = QtGui.QComboBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.powBut.setFont(font)
        self.powBut.setObjectName(_fromUtf8("powBut"))
        self.powBut.addItem(_fromUtf8(""))
        self.powBut.addItem(_fromUtf8(""))
        self.powBut.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.powBut, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 4, 3, 1, 1)
        spacerItem37 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem37, 2, 5, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 6, 1, 1)
        spacerItem38 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem38, 2, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.powTrans = QtGui.QComboBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.powTrans.setFont(font)
        self.powTrans.setObjectName(_fromUtf8("powTrans"))
        self.powTrans.addItem(_fromUtf8(""))
        self.powTrans.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.powTrans, 4, 1, 1, 1)
        self.powOrder = QtGui.QSpinBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.powOrder.setFont(font)
        self.powOrder.setMinimum(1)
        self.powOrder.setMaximum(10)
        self.powOrder.setProperty("value", 3)
        self.powOrder.setObjectName(_fromUtf8("powOrder"))
        self.gridLayout.addWidget(self.powOrder, 2, 4, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.verticalLayout_35.addLayout(self.gridLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem39 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem39)
        self.powRunCustom = QtGui.QPushButton(self.groupBox_6)
        self.powRunCustom.setObjectName(_fromUtf8("powRunCustom"))
        self.horizontalLayout_5.addWidget(self.powRunCustom)
        spacerItem40 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem40)
        self.verticalLayout_35.addLayout(self.horizontalLayout_5)
        self.verticalLayout_36.addWidget(self.groupBox_6)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_11)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_43 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_43.setObjectName(_fromUtf8("verticalLayout_43"))
        self.verticalLayout_42 = QtGui.QVBoxLayout()
        self.verticalLayout_42.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_42.setObjectName(_fromUtf8("verticalLayout_42"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_36 = QtGui.QLabel(self.groupBox_7)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_3.addWidget(self.label_36, 1, 0, 1, 1)
        self.label_35 = QtGui.QLabel(self.groupBox_7)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_3.addWidget(self.label_35, 0, 0, 1, 1)
        self.label_37 = QtGui.QLabel(self.groupBox_7)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_3.addWidget(self.label_37, 1, 2, 1, 1)
        self.powCmap = QtGui.QComboBox(self.groupBox_7)
        self.powCmap.setObjectName(_fromUtf8("powCmap"))
        self.gridLayout_3.addWidget(self.powCmap, 0, 1, 1, 1)
        self.powVmin = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.powVmin.setMinimum(-1000000.0)
        self.powVmin.setMaximum(1000000.0)
        self.powVmin.setSingleStep(0.1)
        self.powVmin.setProperty("value", -1.0)
        self.powVmin.setObjectName(_fromUtf8("powVmin"))
        self.gridLayout_3.addWidget(self.powVmin, 1, 1, 1, 1)
        self.powVmax = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.powVmax.setMinimum(-1000000.0)
        self.powVmax.setMaximum(1000000.0)
        self.powVmax.setSingleStep(0.1)
        self.powVmax.setProperty("value", 1.0)
        self.powVmax.setObjectName(_fromUtf8("powVmax"))
        self.gridLayout_3.addWidget(self.powVmax, 1, 3, 1, 1)
        self.verticalLayout_42.addLayout(self.gridLayout_3)
        self.verticalLayout_43.addLayout(self.verticalLayout_42)
        self.horizontalLayout_45 = QtGui.QHBoxLayout()
        self.horizontalLayout_45.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_45.setObjectName(_fromUtf8("horizontalLayout_45"))
        spacerItem41 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_45.addItem(spacerItem41)
        self.powPltUpd = QtGui.QPushButton(self.groupBox_7)
        self.powPltUpd.setObjectName(_fromUtf8("powPltUpd"))
        self.horizontalLayout_45.addWidget(self.powPltUpd)
        spacerItem42 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_45.addItem(spacerItem42)
        self.verticalLayout_43.addLayout(self.horizontalLayout_45)
        self.verticalLayout_36.addWidget(self.groupBox_7)
        spacerItem43 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_36.addItem(spacerItem43)
        self.verticalLayout_37.addLayout(self.verticalLayout_36)
        self.tabWidget_2.addTab(self.tab_11, _fromUtf8(""))
        self.verticalLayout_16.addWidget(self.tabWidget_2)
        spacerItem44 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem44)
        self.verticalLayout_22.addLayout(self.verticalLayout_16)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.verticalLayout_26 = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout_26.setObjectName(_fromUtf8("verticalLayout_26"))
        self.verticalLayout_25 = QtGui.QVBoxLayout()
        self.verticalLayout_25.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        spacerItem45 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem45)
        self.label_25 = QtGui.QLabel(self.tab_6)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_33.addWidget(self.label_25)
        spacerItem46 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem46)
        self.verticalLayout_25.addLayout(self.horizontalLayout_33)
        self.tabWidget_3 = QtGui.QTabWidget(self.tab_6)
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.verticalLayout_27 = QtGui.QVBoxLayout(self.tab_8)
        self.verticalLayout_27.setObjectName(_fromUtf8("verticalLayout_27"))
        self.groupBox = QtGui.QGroupBox(self.tab_8)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_32 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_32.setObjectName(_fromUtf8("verticalLayout_32"))
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_35.addWidget(self.label_14)
        self.tfFrom = QtGui.QDoubleSpinBox(self.groupBox)
        self.tfFrom.setMaximum(300.0)
        self.tfFrom.setProperty("value", 2.0)
        self.tfFrom.setObjectName(_fromUtf8("tfFrom"))
        self.horizontalLayout_35.addWidget(self.tfFrom)
        spacerItem47 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem47)
        self.label_21 = QtGui.QLabel(self.groupBox)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_35.addWidget(self.label_21)
        self.tfTo = QtGui.QDoubleSpinBox(self.groupBox)
        self.tfTo.setMaximum(300.0)
        self.tfTo.setProperty("value", 100.0)
        self.tfTo.setObjectName(_fromUtf8("tfTo"))
        self.horizontalLayout_35.addWidget(self.tfTo)
        spacerItem48 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem48)
        self.label_24 = QtGui.QLabel(self.groupBox)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_35.addWidget(self.label_24)
        self.tfWidth = QtGui.QDoubleSpinBox(self.groupBox)
        self.tfWidth.setMaximum(300.0)
        self.tfWidth.setProperty("value", 4.0)
        self.tfWidth.setObjectName(_fromUtf8("tfWidth"))
        self.horizontalLayout_35.addWidget(self.tfWidth)
        spacerItem49 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem49)
        self.label_26 = QtGui.QLabel(self.groupBox)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_35.addWidget(self.label_26)
        self.tfStep = QtGui.QDoubleSpinBox(self.groupBox)
        self.tfStep.setMaximum(300.0)
        self.tfStep.setProperty("value", 2.0)
        self.tfStep.setObjectName(_fromUtf8("tfStep"))
        self.horizontalLayout_35.addWidget(self.tfStep)
        self.verticalLayout_32.addLayout(self.horizontalLayout_35)
        self.verticalLayout_27.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_8)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_33 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_33.setObjectName(_fromUtf8("verticalLayout_33"))
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_40.setObjectName(_fromUtf8("horizontalLayout_40"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_40.addWidget(self.label_12)
        self.tfChanNb = QtGui.QSpinBox(self.groupBox_2)
        self.tfChanNb.setObjectName(_fromUtf8("tfChanNb"))
        self.horizontalLayout_40.addWidget(self.tfChanNb)
        spacerItem50 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem50)
        self.verticalLayout_33.addLayout(self.horizontalLayout_40)
        self.verticalLayout_27.addWidget(self.groupBox_2)
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        spacerItem51 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem51)
        self.tfRun = QtGui.QPushButton(self.tab_8)
        self.tfRun.setObjectName(_fromUtf8("tfRun"))
        self.horizontalLayout_36.addWidget(self.tfRun)
        spacerItem52 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem52)
        self.verticalLayout_27.addLayout(self.horizontalLayout_36)
        spacerItem53 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_27.addItem(spacerItem53)
        self.tabWidget_3.addTab(self.tab_8, _fromUtf8(""))
        self.tab_12 = QtGui.QWidget()
        self.tab_12.setObjectName(_fromUtf8("tab_12"))
        self.verticalLayout_40 = QtGui.QVBoxLayout(self.tab_12)
        self.verticalLayout_40.setObjectName(_fromUtf8("verticalLayout_40"))
        self.horizontalLayout_48 = QtGui.QHBoxLayout()
        self.horizontalLayout_48.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_48.setObjectName(_fromUtf8("horizontalLayout_48"))
        spacerItem54 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem54)
        self.tfResume = QtGui.QLabel(self.tab_12)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tfResume.setFont(font)
        self.tfResume.setObjectName(_fromUtf8("tfResume"))
        self.horizontalLayout_48.addWidget(self.tfResume)
        spacerItem55 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem55)
        self.verticalLayout_40.addLayout(self.horizontalLayout_48)
        self.groupBox_10 = QtGui.QGroupBox(self.tab_12)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout_24 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.horizontalLayout_43 = QtGui.QHBoxLayout()
        self.horizontalLayout_43.setObjectName(_fromUtf8("horizontalLayout_43"))
        self.tfBsl = QtGui.QCheckBox(self.groupBox_10)
        self.tfBsl.setObjectName(_fromUtf8("tfBsl"))
        self.horizontalLayout_43.addWidget(self.tfBsl)
        self.tfBslW = QtGui.QWidget(self.groupBox_10)
        self.tfBslW.setObjectName(_fromUtf8("tfBslW"))
        self.horizontalLayout_44 = QtGui.QHBoxLayout(self.tfBslW)
        self.horizontalLayout_44.setObjectName(_fromUtf8("horizontalLayout_44"))
        self.label_32 = QtGui.QLabel(self.tfBslW)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_44.addWidget(self.label_32)
        self.tfBslFrom = QtGui.QSpinBox(self.tfBslW)
        self.tfBslFrom.setMaximum(16777215)
        self.tfBslFrom.setObjectName(_fromUtf8("tfBslFrom"))
        self.horizontalLayout_44.addWidget(self.tfBslFrom)
        self.label_33 = QtGui.QLabel(self.tfBslW)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_44.addWidget(self.label_33)
        self.tfBslTo = QtGui.QSpinBox(self.tfBslW)
        self.tfBslTo.setMaximum(16777215)
        self.tfBslTo.setObjectName(_fromUtf8("tfBslTo"))
        self.horizontalLayout_44.addWidget(self.tfBslTo)
        self.label_34 = QtGui.QLabel(self.tfBslW)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_44.addWidget(self.label_34)
        self.tfNorm = QtGui.QSpinBox(self.tfBslW)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tfNorm.setFont(font)
        self.tfNorm.setMaximum(4)
        self.tfNorm.setProperty("value", 0)
        self.tfNorm.setObjectName(_fromUtf8("tfNorm"))
        self.horizontalLayout_44.addWidget(self.tfNorm)
        self.horizontalLayout_43.addWidget(self.tfBslW)
        self.verticalLayout_24.addLayout(self.horizontalLayout_43)
        self.verticalLayout_40.addWidget(self.groupBox_10)
        self.groupBox_9 = QtGui.QGroupBox(self.tab_12)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.verticalLayout_38 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_38.setObjectName(_fromUtf8("verticalLayout_38"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem56 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem56, 2, 9, 1, 1)
        self.tfCycle = QtGui.QSpinBox(self.groupBox_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tfCycle.setFont(font)
        self.tfCycle.setMinimum(1)
        self.tfCycle.setMaximum(20)
        self.tfCycle.setProperty("value", 3)
        self.tfCycle.setObjectName(_fromUtf8("tfCycle"))
        self.gridLayout_2.addWidget(self.tfCycle, 2, 7, 1, 1)
        self.tfDetrend = QtGui.QCheckBox(self.groupBox_9)
        self.tfDetrend.setText(_fromUtf8(""))
        self.tfDetrend.setObjectName(_fromUtf8("tfDetrend"))
        self.gridLayout_2.addWidget(self.tfDetrend, 5, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 5, 0, 1, 1)
        self.tfWidthW = QtGui.QSpinBox(self.groupBox_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tfWidthW.setFont(font)
        self.tfWidthW.setMinimum(1)
        self.tfWidthW.setProperty("value", 7)
        self.tfWidthW.setObjectName(_fromUtf8("tfWidthW"))
        self.gridLayout_2.addWidget(self.tfWidthW, 4, 4, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 2, 3, 1, 1)
        self.tfBut = QtGui.QComboBox(self.groupBox_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tfBut.setFont(font)
        self.tfBut.setObjectName(_fromUtf8("tfBut"))
        self.tfBut.addItem(_fromUtf8(""))
        self.tfBut.addItem(_fromUtf8(""))
        self.tfBut.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.tfBut, 2, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 4, 3, 1, 1)
        spacerItem57 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem57, 2, 5, 1, 1)
        self.label_29 = QtGui.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_2.addWidget(self.label_29, 2, 6, 1, 1)
        spacerItem58 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem58, 2, 2, 1, 1)
        self.label_30 = QtGui.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_2.addWidget(self.label_30, 4, 0, 1, 1)
        self.tfTrans = QtGui.QComboBox(self.groupBox_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tfTrans.setFont(font)
        self.tfTrans.setObjectName(_fromUtf8("tfTrans"))
        self.tfTrans.addItem(_fromUtf8(""))
        self.tfTrans.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.tfTrans, 4, 1, 1, 1)
        self.tfOrder = QtGui.QSpinBox(self.groupBox_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tfOrder.setFont(font)
        self.tfOrder.setMinimum(1)
        self.tfOrder.setMaximum(10)
        self.tfOrder.setProperty("value", 3)
        self.tfOrder.setObjectName(_fromUtf8("tfOrder"))
        self.gridLayout_2.addWidget(self.tfOrder, 2, 4, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_2.addWidget(self.label_31, 2, 0, 1, 1)
        self.verticalLayout_38.addLayout(self.gridLayout_2)
        self.horizontalLayout_47 = QtGui.QHBoxLayout()
        self.horizontalLayout_47.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_47.setObjectName(_fromUtf8("horizontalLayout_47"))
        spacerItem59 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_47.addItem(spacerItem59)
        self.tfRunCustom = QtGui.QPushButton(self.groupBox_9)
        self.tfRunCustom.setObjectName(_fromUtf8("tfRunCustom"))
        self.horizontalLayout_47.addWidget(self.tfRunCustom)
        spacerItem60 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_47.addItem(spacerItem60)
        self.verticalLayout_38.addLayout(self.horizontalLayout_47)
        self.verticalLayout_40.addWidget(self.groupBox_9)
        self.groupBox_8 = QtGui.QGroupBox(self.tab_12)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_39 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_39.setObjectName(_fromUtf8("verticalLayout_39"))
        self.verticalLayout_44 = QtGui.QVBoxLayout()
        self.verticalLayout_44.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_44.setObjectName(_fromUtf8("verticalLayout_44"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_38 = QtGui.QLabel(self.groupBox_8)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_4.addWidget(self.label_38, 1, 0, 1, 1)
        self.label_39 = QtGui.QLabel(self.groupBox_8)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_4.addWidget(self.label_39, 0, 0, 1, 1)
        self.label_40 = QtGui.QLabel(self.groupBox_8)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_4.addWidget(self.label_40, 1, 2, 1, 1)
        self.tfCmap = QtGui.QComboBox(self.groupBox_8)
        self.tfCmap.setObjectName(_fromUtf8("tfCmap"))
        self.gridLayout_4.addWidget(self.tfCmap, 0, 1, 1, 1)
        self.tfVmin = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.tfVmin.setMinimum(-1000000.0)
        self.tfVmin.setMaximum(1000000.0)
        self.tfVmin.setSingleStep(0.1)
        self.tfVmin.setProperty("value", -1.0)
        self.tfVmin.setObjectName(_fromUtf8("tfVmin"))
        self.gridLayout_4.addWidget(self.tfVmin, 1, 1, 1, 1)
        self.tfVmax = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.tfVmax.setMinimum(-1000000.0)
        self.tfVmax.setMaximum(1000000.0)
        self.tfVmax.setSingleStep(0.1)
        self.tfVmax.setProperty("value", 1.0)
        self.tfVmax.setObjectName(_fromUtf8("tfVmax"))
        self.gridLayout_4.addWidget(self.tfVmax, 1, 3, 1, 1)
        self.verticalLayout_44.addLayout(self.gridLayout_4)
        self.verticalLayout_39.addLayout(self.verticalLayout_44)
        self.horizontalLayout_46 = QtGui.QHBoxLayout()
        self.horizontalLayout_46.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_46.setObjectName(_fromUtf8("horizontalLayout_46"))
        spacerItem61 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_46.addItem(spacerItem61)
        self.tfPltUpd = QtGui.QPushButton(self.groupBox_8)
        self.tfPltUpd.setObjectName(_fromUtf8("tfPltUpd"))
        self.horizontalLayout_46.addWidget(self.tfPltUpd)
        spacerItem62 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_46.addItem(spacerItem62)
        self.verticalLayout_39.addLayout(self.horizontalLayout_46)
        self.verticalLayout_40.addWidget(self.groupBox_8)
        spacerItem63 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_40.addItem(spacerItem63)
        self.tabWidget_3.addTab(self.tab_12, _fromUtf8(""))
        self.verticalLayout_25.addWidget(self.tabWidget_3)
        self.verticalLayout_26.addLayout(self.verticalLayout_25)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.verticalLayout_41.addWidget(self.tabWidget)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, 50, -1)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.userMsg = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.userMsg.setFont(font)
        self.userMsg.setStyleSheet(_fromUtf8(""))
        self.userMsg.setObjectName(_fromUtf8("userMsg"))
        self.horizontalLayout_9.addWidget(self.userMsg)
        self.verticalLayout_41.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_2.addLayout(self.verticalLayout_41)
        self.mplwindow = QtGui.QWidget(self.centralwidget)
        self.mplwindow.setMinimumSize(QtCore.QSize(400, 0))
        self.mplwindow.setObjectName(_fromUtf8("mplwindow"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.mplwindow)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.mplbox = QtGui.QVBoxLayout()
        self.mplbox.setContentsMargins(0, -1, -1, -1)
        self.mplbox.setObjectName(_fromUtf8("mplbox"))
        self.verticalLayout_9.addLayout(self.mplbox)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        spacerItem64 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem64)
        self.cleanAx = QtGui.QPushButton(self.mplwindow)
        self.cleanAx.setObjectName(_fromUtf8("cleanAx"))
        self.horizontalLayout_34.addWidget(self.cleanAx)
        spacerItem65 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem65)
        self.getConfig = QtGui.QPushButton(self.mplwindow)
        self.getConfig.setObjectName(_fromUtf8("getConfig"))
        self.horizontalLayout_34.addWidget(self.getConfig)
        spacerItem66 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem66)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horizontalLayout_34.addLayout(self.horizontalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_34)
        self.verticalLayout_2.addLayout(self.verticalLayout_9)
        self.horizontalLayout_2.addWidget(self.mplwindow)
        bpui.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(bpui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1310, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuOption = QtGui.QMenu(self.menubar)
        self.menuOption.setObjectName(_fromUtf8("menuOption"))
        self.menuMode = QtGui.QMenu(self.menubar)
        self.menuMode.setObjectName(_fromUtf8("menuMode"))
        self.menuDisplay = QtGui.QMenu(self.menubar)
        self.menuDisplay.setObjectName(_fromUtf8("menuDisplay"))
        bpui.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(bpui)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        bpui.setStatusBar(self.statusbar)
        self.actionAdvanced = QtGui.QAction(bpui)
        self.actionAdvanced.setCheckable(True)
        self.actionAdvanced.setObjectName(_fromUtf8("actionAdvanced"))
        self.actionDebugger = QtGui.QAction(bpui)
        self.actionDebugger.setObjectName(_fromUtf8("actionDebugger"))
        self.actionTab_settings = QtGui.QAction(bpui)
        self.actionTab_settings.setCheckable(True)
        self.actionTab_settings.setChecked(True)
        self.actionTab_settings.setObjectName(_fromUtf8("actionTab_settings"))
        self.actionLoadPow = QtGui.QAction(bpui)
        self.actionLoadPow.setObjectName(_fromUtf8("actionLoadPow"))
        self.menuOption.addAction(self.actionLoadPow)
        self.menuMode.addAction(self.actionAdvanced)
        self.menuMode.addAction(self.actionDebugger)
        self.menuDisplay.addAction(self.actionTab_settings)
        self.menubar.addAction(self.menuOption.menuAction())
        self.menubar.addAction(self.menuDisplay.menuAction())
        self.menubar.addAction(self.menuMode.menuAction())

        self.retranslateUi(bpui)
        self.tabWidget.setCurrentIndex(3)
        self.tabWidget_2.setCurrentIndex(2)
        self.tabWidget_3.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(bpui)

    def retranslateUi(self, bpui):
        bpui.setWindowTitle(_translate("bpui", "brainpipe - Features", None))
        self.tabWidget.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Time Domain Analysis</span> (ERP...)</p></body></html>", None))
        self.uicd.setText(_translate("bpui", "Change current directory", None))
        self.label_13.setText(_translate("bpui", "Sampling frequency", None))
        self.label_28.setText(_translate("bpui", "Variale to use for data", None))
        self.label_7.setText(_translate("bpui", "<html><head/><body><p><span style=\" text-decoration: underline;\">Contact</span>: <span style=\" color:#0000ff;\">e.combrisson@gmail.com</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("bpui", "Data", None))
        self.label_23.setText(_translate("bpui", "Time Domain Analysis", None))
        self.rawPanelBox.setText(_translate("bpui", "Raw data", None))
        self.erpPanelBox.setText(_translate("bpui", "ERP", None))
        self.rawAcross.setText(_translate("bpui", "Across chanels", None))
        self.rawPer.setText(_translate("bpui", "Per channel", None))
        self.label_19.setText(_translate("bpui", "Channel: ", None))
        self.erpAcross.setText(_translate("bpui", "Across chanels", None))
        self.erpPer.setText(_translate("bpui", "Per channel", None))
        self.erpSTD.setText(_translate("bpui", "std", None))
        self.erpSEM.setText(_translate("bpui", "sem", None))
        self.label_20.setText(_translate("bpui", "Channel: ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("bpui", "TDA", None))
        self.label_15.setText(_translate("bpui", "Frequency Domain Analysis", None))
        self.groupBox_3.setTitle(_translate("bpui", "Frequency bands", None))
        self.powTable.setSortingEnabled(False)
        item = self.powTable.verticalHeaderItem(0)
        item.setText(_translate("bpui", "1", None))
        item = self.powTable.verticalHeaderItem(1)
        item.setText(_translate("bpui", "2", None))
        item = self.powTable.verticalHeaderItem(2)
        item.setText(_translate("bpui", "3", None))
        item = self.powTable.verticalHeaderItem(3)
        item.setText(_translate("bpui", "4", None))
        item = self.powTable.verticalHeaderItem(4)
        item.setText(_translate("bpui", "5", None))
        item = self.powTable.verticalHeaderItem(5)
        item.setText(_translate("bpui", "6", None))
        item = self.powTable.horizontalHeaderItem(0)
        item.setText(_translate("bpui", "Name", None))
        item = self.powTable.horizontalHeaderItem(1)
        item.setText(_translate("bpui", "From", None))
        item = self.powTable.horizontalHeaderItem(2)
        item.setText(_translate("bpui", "To", None))
        __sortingEnabled = self.powTable.isSortingEnabled()
        self.powTable.setSortingEnabled(False)
        item = self.powTable.item(0, 0)
        item.setText(_translate("bpui", "Delta", None))
        item = self.powTable.item(0, 1)
        item.setText(_translate("bpui", "2.0", None))
        item = self.powTable.item(0, 2)
        item.setText(_translate("bpui", "4.0", None))
        item = self.powTable.item(1, 0)
        item.setText(_translate("bpui", "Theta", None))
        item = self.powTable.item(1, 1)
        item.setText(_translate("bpui", "5.0", None))
        item = self.powTable.item(1, 2)
        item.setText(_translate("bpui", "7.0", None))
        item = self.powTable.item(2, 0)
        item.setText(_translate("bpui", "Alpha", None))
        item = self.powTable.item(2, 1)
        item.setText(_translate("bpui", "8.0", None))
        item = self.powTable.item(2, 2)
        item.setText(_translate("bpui", "13.0", None))
        item = self.powTable.item(3, 0)
        item.setText(_translate("bpui", "Beta", None))
        item = self.powTable.item(3, 1)
        item.setText(_translate("bpui", "13.0", None))
        item = self.powTable.item(3, 2)
        item.setText(_translate("bpui", "30.0", None))
        item = self.powTable.item(4, 0)
        item.setText(_translate("bpui", "Gamma1", None))
        item = self.powTable.item(4, 1)
        item.setText(_translate("bpui", "30.0", None))
        item = self.powTable.item(4, 2)
        item.setText(_translate("bpui", "60.0", None))
        item = self.powTable.item(5, 0)
        item.setText(_translate("bpui", "Gamma2", None))
        item = self.powTable.item(5, 1)
        item.setText(_translate("bpui", "60.0", None))
        item = self.powTable.item(5, 2)
        item.setText(_translate("bpui", "90.0", None))
        self.powTable.setSortingEnabled(__sortingEnabled)
        self.powFceAdd.setText(_translate("bpui", "Add", None))
        self.powFceRm.setText(_translate("bpui", "Remove", None))
        self.groupBox_5.setTitle(_translate("bpui", "Compute for", None))
        self.powAllChan.setText(_translate("bpui", "All channels", None))
        self.powSelectChan.setText(_translate("bpui", "Select channel", None))
        self.powFceUp.setText(_translate("bpui", "Update", None))
        self.powRun.setText(_translate("bpui", "Run (with basic setup)", None))
        self.powLoad.setText(_translate("bpui", "Load", None))
        self.powSave.setText(_translate("bpui", "Save", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("bpui", "Settings", None))
        self.label_11.setText(_translate("bpui", "Frequency to plot", None))
        self.powAcross.setText(_translate("bpui", "Across channel", None))
        self.powPer1D.setText(_translate("bpui", "Per channel (1D)", None))
        self.powPer2D.setText(_translate("bpui", "Per channel (2D)", None))
        self.powTopo.setText(_translate("bpui", "Topoplot", None))
        self.label_22.setText(_translate("bpui", "Channel: ", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("bpui", "Plot", None))
        self.groupBox_4.setTitle(_translate("bpui", "Normalization", None))
        self.powBsl.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Normalize the power using a baseline</span></p></body></html>", None))
        self.powBsl.setText(_translate("bpui", "Baseline", None))
        self.label_8.setText(_translate("bpui", "From", None))
        self.powBslFrom.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Define where the baseline start</span> (in SAMPLE)</p></body></html>", None))
        self.label_9.setText(_translate("bpui", "To", None))
        self.powBslTo.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Define where the baseline finish</span> (in SAMPLE)</p></body></html>", None))
        self.label_10.setText(_translate("bpui", "Normalization", None))
        self.powNorm.setToolTip(_translate("bpui", "<html><head/><body><p>Définit le type de normalisation pour corriger la puissance par la baseline</p><p>        0 : Pas de normalisation</p><p>        1 : Soustraction de la moyenne de la baseline</p><p>        2 : Division par la moyenne de la baseline</p><p>        3 : Soustraction puis division par la moyenne de la baseline</p><p>        4 : Soustraction de la moyenne de la baseline puis division par la déviation de la baseline (Z-score)</p></body></html>", None))
        self.groupBox_6.setTitle(_translate("bpui", "Filtering", None))
        self.powCycle.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Nombre de cycle (pour l\'option de filtrage firls)</span></p><p><span style=\" text-decoration: underline;\">Effet :</span> Nombre de cycles à considérer pour calculer l\'ordre du filtre. Pour des basses fréquences (delta / theta / alpha / beta), on préfèrera des valeurs proches de 3. Pour des hautes fréquences (&gt;= 60), un plus grand nombre de cycles peut améliorer l\'estimation de puissance. 6 cycles est une bonne valeur (cf. Bahramisharif et al., 2013 )</p></body></html>", None))
        self.powDetrend.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Permet d\'applique un </span><span style=\" font-weight:600; font-style:italic;\">detrending</span><span style=\" font-weight:600;\"> au signal</span></p></body></html>", None))
        self.label_5.setText(_translate("bpui", "Detrend", None))
        self.powWidthW.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Taille de l\'ondelette</span></p></body></html>", None))
        self.label_3.setText(_translate("bpui", "Order", None))
        self.powBut.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Type de filtre pour extraire les informations spectrales.</span></p><p><span style=\" text-decoration: underline;\">- butter:</span> filtre Butterworth (bon compromis entre vitesse et précision mais introduit un décalage)</p><p><span style=\" text-decoration: underline;\">- bessel: </span> filtre de bessel (introduit un décalage)</p><p><span style=\" text-decoration: underline;\">- fir1:</span> Finite Response Filter - Least Square (cf. Delorme and Makeig, 2004) - filtre très précis, qui conserve la phase mais deux fois plus lent</p></body></html>", None))
        self.powBut.setWhatsThis(_translate("bpui", "<html><head/><body><p><br/></p></body></html>", None))
        self.powBut.setItemText(0, _translate("bpui", "butter", None))
        self.powBut.setItemText(1, _translate("bpui", "bessel", None))
        self.powBut.setItemText(2, _translate("bpui", "fir1", None))
        self.label_6.setText(_translate("bpui", "Width", None))
        self.label_4.setText(_translate("bpui", "Cycle", None))
        self.label_2.setText(_translate("bpui", "Transformation", None))
        self.powTrans.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Méthode de calcul de puissance. Ces méthodes permettent de passer un signal du domaine réel au domaine complexe. Ces deux méthodes offrent des résultats comparables</span></p><p><span style=\" text-decoration: underline;\">- Wavelet :</span> transformée en ondelettes (voir Thomas pour plus de détail)</p><p><span style=\" text-decoration: underline;\">- Hilbert :</span> la transformée d\'Hilbert permet de décomposer un signal en phase / amplitude</p></body></html>", None))
        self.powTrans.setItemText(0, _translate("bpui", "hilbert1", None))
        self.powTrans.setItemText(1, _translate("bpui", "wavelet", None))
        self.powOrder.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Ordre du filtre Butterworth ou Bessel </span>(pas d\'effet sur firls)</p><p><span style=\" text-decoration: underline;\">Effet:</span> Filtrage plus ou moins efficace mais peut engendrer des distorsions (ou artefact) dans le signal. De plus, un ordre trop grand peut considérablement augmenter le temps de calcul</p></body></html>", None))
        self.label.setText(_translate("bpui", "Filter", None))
        self.powRunCustom.setText(_translate("bpui", "Run (with advanced setup)", None))
        self.groupBox_7.setTitle(_translate("bpui", "Visualization", None))
        self.label_36.setText(_translate("bpui", "vmin", None))
        self.label_35.setText(_translate("bpui", "Colormap", None))
        self.label_37.setText(_translate("bpui", "vmax", None))
        self.powPltUpd.setText(_translate("bpui", "Update plot", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_11), _translate("bpui", "Advanced", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("bpui", "FDA", None))
        self.label_25.setText(_translate("bpui", "Time Frequency Analysis", None))
        self.groupBox.setTitle(_translate("bpui", "Frequency", None))
        self.label_14.setText(_translate("bpui", "From:", None))
        self.label_21.setText(_translate("bpui", "To:", None))
        self.label_24.setText(_translate("bpui", "Width:", None))
        self.label_26.setText(_translate("bpui", "Step:", None))
        self.groupBox_2.setTitle(_translate("bpui", "Compute for", None))
        self.label_12.setText(_translate("bpui", "Channel", None))
        self.tfRun.setText(_translate("bpui", "Run (with basic setup))", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("bpui", "Settings", None))
        self.tfResume.setText(_translate("bpui", "\'\'\'", None))
        self.groupBox_10.setTitle(_translate("bpui", "Normalization", None))
        self.tfBsl.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Normalize the power using a baseline</span></p></body></html>", None))
        self.tfBsl.setText(_translate("bpui", "Baseline", None))
        self.label_32.setText(_translate("bpui", "From", None))
        self.tfBslFrom.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Define where the baseline start</span> (in SAMPLE)</p></body></html>", None))
        self.label_33.setText(_translate("bpui", "To", None))
        self.tfBslTo.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Define where the baseline finish</span> (in SAMPLE)</p></body></html>", None))
        self.label_34.setText(_translate("bpui", "Normalization", None))
        self.tfNorm.setToolTip(_translate("bpui", "<html><head/><body><p>Définit le type de normalisation pour corriger la puissance par la baseline</p><p>        0 : Pas de normalisation</p><p>        1 : Soustraction de la moyenne de la baseline</p><p>        2 : Division par la moyenne de la baseline</p><p>        3 : Soustraction puis division par la moyenne de la baseline</p><p>        4 : Soustraction de la moyenne de la baseline puis division par la déviation de la baseline (Z-score)</p></body></html>", None))
        self.groupBox_9.setTitle(_translate("bpui", "Filtering", None))
        self.tfCycle.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Nombre de cycle (pour l\'option de filtrage firls)</span></p><p><span style=\" text-decoration: underline;\">Effet :</span> Nombre de cycles à considérer pour calculer l\'ordre du filtre. Pour des basses fréquences (delta / theta / alpha / beta), on préfèrera des valeurs proches de 3. Pour des hautes fréquences (&gt;= 60), un plus grand nombre de cycles peut améliorer l\'estimation de puissance. 6 cycles est une bonne valeur (cf. Bahramisharif et al., 2013 )</p></body></html>", None))
        self.tfDetrend.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Permet d\'applique un </span><span style=\" font-weight:600; font-style:italic;\">detrending</span><span style=\" font-weight:600;\"> au signal</span></p></body></html>", None))
        self.label_16.setText(_translate("bpui", "Detrend", None))
        self.tfWidthW.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Taille de l\'ondelette</span></p></body></html>", None))
        self.label_17.setText(_translate("bpui", "Order", None))
        self.tfBut.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Type de filtre pour extraire les informations spectrales.</span></p><p><span style=\" text-decoration: underline;\">- butter:</span> filtre Butterworth (bon compromis entre vitesse et précision mais introduit un décalage)</p><p><span style=\" text-decoration: underline;\">- bessel: </span> filtre de bessel (introduit un décalage)</p><p><span style=\" text-decoration: underline;\">- fir1:</span> Finite Response Filter - Least Square (cf. Delorme and Makeig, 2004) - filtre très précis, qui conserve la phase mais deux fois plus lent</p></body></html>", None))
        self.tfBut.setWhatsThis(_translate("bpui", "<html><head/><body><p><br/></p></body></html>", None))
        self.tfBut.setItemText(0, _translate("bpui", "butter", None))
        self.tfBut.setItemText(1, _translate("bpui", "bessel", None))
        self.tfBut.setItemText(2, _translate("bpui", "fir1", None))
        self.label_18.setText(_translate("bpui", "Width", None))
        self.label_29.setText(_translate("bpui", "Cycle", None))
        self.label_30.setText(_translate("bpui", "Transformation", None))
        self.tfTrans.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Méthode de calcul de puissance. Ces méthodes permettent de passer un signal du domaine réel au domaine complexe. Ces deux méthodes offrent des résultats comparables</span></p><p><span style=\" text-decoration: underline;\">- Wavelet :</span> transformée en ondelettes (voir Thomas pour plus de détail)</p><p><span style=\" text-decoration: underline;\">- Hilbert :</span> la transformée d\'Hilbert permet de décomposer un signal en phase / amplitude</p></body></html>", None))
        self.tfTrans.setItemText(0, _translate("bpui", "hilbert1", None))
        self.tfTrans.setItemText(1, _translate("bpui", "wavelet", None))
        self.tfOrder.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Ordre du filtre Butterworth ou Bessel </span>(pas d\'effet sur firls)</p><p><span style=\" text-decoration: underline;\">Effet:</span> Filtrage plus ou moins efficace mais peut engendrer des distorsions (ou artefact) dans le signal. De plus, un ordre trop grand peut considérablement augmenter le temps de calcul</p></body></html>", None))
        self.label_31.setText(_translate("bpui", "Filter", None))
        self.tfRunCustom.setText(_translate("bpui", "Run (with advanced setup)", None))
        self.groupBox_8.setTitle(_translate("bpui", "Visualization", None))
        self.label_38.setText(_translate("bpui", "vmin", None))
        self.label_39.setText(_translate("bpui", "Colormap", None))
        self.label_40.setText(_translate("bpui", "vmax", None))
        self.tfPltUpd.setText(_translate("bpui", "Update plot", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_12), _translate("bpui", "Advanced", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("bpui", "TFR", None))
        self.userMsg.setText(_translate("bpui", "plkj", None))
        self.cleanAx.setText(_translate("bpui", "clean", None))
        self.getConfig.setText(_translate("bpui", "Get config", None))
        self.menuOption.setTitle(_translate("bpui", "Option", None))
        self.menuMode.setTitle(_translate("bpui", "Mode", None))
        self.menuDisplay.setTitle(_translate("bpui", "Display", None))
        self.actionAdvanced.setText(_translate("bpui", "Advanced", None))
        self.actionDebugger.setText(_translate("bpui", "Debugger", None))
        self.actionTab_settings.setText(_translate("bpui", "Tab settings", None))
        self.actionTab_settings.setShortcut(_translate("bpui", "Ctrl+T", None))
        self.actionLoadPow.setText(_translate("bpui", "Load power file", None))

