# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bpfeat.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_bpui(object):
    def setupUi(self, bpui):
        bpui.setObjectName(_fromUtf8("bpui"))
        bpui.resize(1310, 893)
        self.centralwidget = QtGui.QWidget(bpui)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(550, 16777215))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_3)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.uicd = QtGui.QPushButton(self.tab_2)
        self.uicd.setObjectName(_fromUtf8("uicd"))
        self.horizontalLayout_11.addWidget(self.uicd)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.label_26 = QtGui.QLabel(self.tab_2)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_12.addWidget(self.label_26)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_12)
        self.treeFiles = QtGui.QTreeView(self.tab_2)
        self.treeFiles.setObjectName(_fromUtf8("treeFiles"))
        self.verticalLayout_11.addWidget(self.treeFiles)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem4)
        self.label_27 = QtGui.QLabel(self.tab_2)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_13.addWidget(self.label_27)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.verticalLayout_11.addLayout(self.horizontalLayout_13)
        self.widget = QtGui.QWidget(self.tab_2)
        self.widget.setMinimumSize(QtCore.QSize(0, 200))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_28 = QtGui.QLabel(self.widget)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_14.addWidget(self.label_28)
        self.selectData = QtGui.QComboBox(self.widget)
        self.selectData.setObjectName(_fromUtf8("selectData"))
        self.horizontalLayout_14.addWidget(self.selectData)
        self.dataShape = QtGui.QLabel(self.widget)
        self.dataShape.setObjectName(_fromUtf8("dataShape"))
        self.horizontalLayout_14.addWidget(self.dataShape)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem6)
        self.verticalLayout_12.addLayout(self.horizontalLayout_14)
        self.addDataW = QtGui.QWidget(self.widget)
        self.addDataW.setObjectName(_fromUtf8("addDataW"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.addDataW)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_13 = QtGui.QLabel(self.addDataW)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_15.addWidget(self.label_13)
        self.selectSf = QtGui.QDoubleSpinBox(self.addDataW)
        self.selectSf.setMaximum(500000.0)
        self.selectSf.setProperty("value", 1000.0)
        self.selectSf.setObjectName(_fromUtf8("selectSf"))
        self.horizontalLayout_15.addWidget(self.selectSf)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem7)
        self.verticalLayout_14.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_29 = QtGui.QLabel(self.addDataW)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_16.addWidget(self.label_29)
        self.selectName = QtGui.QLineEdit(self.addDataW)
        self.selectName.setObjectName(_fromUtf8("selectName"))
        self.horizontalLayout_16.addWidget(self.selectName)
        self.verticalLayout_14.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem8)
        self.addNewData = QtGui.QPushButton(self.addDataW)
        self.addNewData.setObjectName(_fromUtf8("addNewData"))
        self.horizontalLayout_17.addWidget(self.addNewData)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem9)
        self.verticalLayout_14.addLayout(self.horizontalLayout_17)
        self.verticalLayout_12.addWidget(self.addDataW)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem10)
        self.datasetValid = QtGui.QLabel(self.widget)
        self.datasetValid.setObjectName(_fromUtf8("datasetValid"))
        self.horizontalLayout_18.addWidget(self.datasetValid)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem11)
        self.verticalLayout_12.addLayout(self.horizontalLayout_18)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.verticalLayout_11.addWidget(self.widget)
        self.verticalLayout_4.addLayout(self.verticalLayout_11)
        self.verticalLayout_10.addLayout(self.verticalLayout_4)
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.tab_8)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.sumTable = QtGui.QTableWidget(self.tab_8)
        self.sumTable.setObjectName(_fromUtf8("sumTable"))
        self.sumTable.setColumnCount(3)
        self.sumTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.sumTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.sumTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.sumTable.setHorizontalHeaderItem(2, item)
        self.verticalLayout_15.addWidget(self.sumTable)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem12)
        self.rmDataset = QtGui.QPushButton(self.tab_8)
        self.rmDataset.setObjectName(_fromUtf8("rmDataset"))
        self.horizontalLayout_19.addWidget(self.rmDataset)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem13)
        self.verticalLayout_15.addLayout(self.horizontalLayout_19)
        self.verticalLayout_16.addLayout(self.verticalLayout_15)
        self.tabWidget_2.addTab(self.tab_8, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.tabWidget_2.addTab(self.tab_7, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.label_19 = QtGui.QLabel(self.tab_4)
        self.label_19.setGeometry(QtCore.QRect(0, 190, 531, 101))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.tab_4)
        self.label_20.setGeometry(QtCore.QRect(0, 40, 501, 121))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_23 = QtGui.QLabel(self.tab_4)
        self.label_23.setGeometry(QtCore.QRect(160, 20, 231, 17))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.label_21 = QtGui.QLabel(self.tab_5)
        self.label_21.setGeometry(QtCore.QRect(10, 30, 281, 17))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.tab_5)
        self.label_22.setGeometry(QtCore.QRect(10, 80, 281, 17))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_24 = QtGui.QLabel(self.tab_5)
        self.label_24.setGeometry(QtCore.QRect(260, 60, 231, 17))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.label_16 = QtGui.QLabel(self.tab_6)
        self.label_16.setGeometry(QtCore.QRect(80, 90, 231, 17))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.tab_6)
        self.label_17.setGeometry(QtCore.QRect(80, 130, 231, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.tab_6)
        self.label_18.setGeometry(QtCore.QRect(80, 170, 391, 17))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_25 = QtGui.QLabel(self.tab_6)
        self.label_25.setGeometry(QtCore.QRect(190, 30, 231, 17))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.toolBox = QtGui.QToolBox(self.tab)
        self.toolBox.setEnabled(True)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.uipowTab = QtGui.QWidget()
        self.uipowTab.setGeometry(QtCore.QRect(0, 0, 528, 627))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.uipowTab.setFont(font)
        self.uipowTab.setObjectName(_fromUtf8("uipowTab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.uipowTab)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_3 = QtGui.QGroupBox(self.uipowTab)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem14)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.powTable = QtGui.QTableWidget(self.groupBox_3)
        self.powTable.setMinimumSize(QtCore.QSize(400, 0))
        self.powTable.setObjectName(_fromUtf8("powTable"))
        self.powTable.setColumnCount(3)
        self.powTable.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.powTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.powTable.setItem(4, 2, item)
        self.horizontalLayout_4.addWidget(self.powTable)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem16)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem17)
        self.powFceAdd = QtGui.QPushButton(self.groupBox_3)
        self.powFceAdd.setObjectName(_fromUtf8("powFceAdd"))
        self.horizontalLayout.addWidget(self.powFceAdd)
        self.powFceRm = QtGui.QPushButton(self.groupBox_3)
        self.powFceRm.setObjectName(_fromUtf8("powFceRm"))
        self.horizontalLayout.addWidget(self.powFceRm)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem18)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.uipowTab)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.powBsl = QtGui.QCheckBox(self.groupBox_4)
        self.powBsl.setObjectName(_fromUtf8("powBsl"))
        self.horizontalLayout_8.addWidget(self.powBsl)
        self.powBslW = QtGui.QWidget(self.groupBox_4)
        self.powBslW.setObjectName(_fromUtf8("powBslW"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.powBslW)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_8 = QtGui.QLabel(self.powBslW)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_9.addWidget(self.label_8)
        self.powBslFrom = QtGui.QSpinBox(self.powBslW)
        self.powBslFrom.setMaximum(16777215)
        self.powBslFrom.setObjectName(_fromUtf8("powBslFrom"))
        self.horizontalLayout_9.addWidget(self.powBslFrom)
        self.label_9 = QtGui.QLabel(self.powBslW)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_9.addWidget(self.label_9)
        self.powBslTo = QtGui.QSpinBox(self.powBslW)
        self.powBslTo.setMaximum(16777215)
        self.powBslTo.setObjectName(_fromUtf8("powBslTo"))
        self.horizontalLayout_9.addWidget(self.powBslTo)
        self.horizontalLayout_8.addWidget(self.powBslW)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem19)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_8)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.powAdv = QtGui.QCheckBox(self.uipowTab)
        self.powAdv.setObjectName(_fromUtf8("powAdv"))
        self.verticalLayout_6.addWidget(self.powAdv)
        self.powAdvW = QtGui.QWidget(self.uipowTab)
        self.powAdvW.setObjectName(_fromUtf8("powAdvW"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.powAdvW)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_5 = QtGui.QGroupBox(self.powAdvW)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem20)
        self.powResume = QtGui.QLabel(self.groupBox_5)
        self.powResume.setStyleSheet(_fromUtf8("color: rgb(170, 0, 0);"))
        self.powResume.setObjectName(_fromUtf8("powResume"))
        self.horizontalLayout_6.addWidget(self.powResume)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem21)
        self.verticalLayout_7.addWidget(self.groupBox_5)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem22, 3, 9, 1, 1)
        self.powCycle = QtGui.QSpinBox(self.powAdvW)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.powCycle.setFont(font)
        self.powCycle.setMinimum(1)
        self.powCycle.setMaximum(20)
        self.powCycle.setProperty("value", 3)
        self.powCycle.setObjectName(_fromUtf8("powCycle"))
        self.gridLayout.addWidget(self.powCycle, 3, 7, 1, 1)
        self.label_3 = QtGui.QLabel(self.powAdvW)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 3, 1, 1)
        self.powBut = QtGui.QComboBox(self.powAdvW)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.powBut.setFont(font)
        self.powBut.setObjectName(_fromUtf8("powBut"))
        self.powBut.addItem(_fromUtf8(""))
        self.powBut.addItem(_fromUtf8(""))
        self.powBut.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.powBut, 3, 1, 1, 1)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem23, 3, 5, 1, 1)
        self.label_4 = QtGui.QLabel(self.powAdvW)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 6, 1, 1)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem24, 3, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.powAdvW)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.powTrans = QtGui.QComboBox(self.powAdvW)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.powTrans.setFont(font)
        self.powTrans.setObjectName(_fromUtf8("powTrans"))
        self.powTrans.addItem(_fromUtf8(""))
        self.powTrans.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.powTrans, 5, 1, 1, 1)
        self.powOrder = QtGui.QSpinBox(self.powAdvW)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.powOrder.setFont(font)
        self.powOrder.setMinimum(1)
        self.powOrder.setMaximum(10)
        self.powOrder.setProperty("value", 3)
        self.powOrder.setObjectName(_fromUtf8("powOrder"))
        self.gridLayout.addWidget(self.powOrder, 3, 4, 1, 1)
        self.label = QtGui.QLabel(self.powAdvW)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.powAdvW)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.powDetrend = QtGui.QCheckBox(self.powAdvW)
        self.powDetrend.setText(_fromUtf8(""))
        self.powDetrend.setObjectName(_fromUtf8("powDetrend"))
        self.gridLayout.addWidget(self.powDetrend, 6, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.powAdvW)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 5, 3, 1, 1)
        self.powWidth = QtGui.QSpinBox(self.powAdvW)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.powWidth.setFont(font)
        self.powWidth.setMinimum(1)
        self.powWidth.setProperty("value", 7)
        self.powWidth.setObjectName(_fromUtf8("powWidth"))
        self.gridLayout.addWidget(self.powWidth, 5, 4, 1, 1)
        self.label_10 = QtGui.QLabel(self.powAdvW)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.powNorm = QtGui.QSpinBox(self.powAdvW)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.powNorm.setFont(font)
        self.powNorm.setMaximum(4)
        self.powNorm.setProperty("value", 3)
        self.powNorm.setObjectName(_fromUtf8("powNorm"))
        self.gridLayout.addWidget(self.powNorm, 0, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.verticalLayout_6.addWidget(self.powAdvW)
        self.toolBox.addItem(self.uipowTab, _fromUtf8(""))
        self.uiphaTab = QtGui.QWidget()
        self.uiphaTab.setEnabled(False)
        self.uiphaTab.setGeometry(QtCore.QRect(0, 0, 528, 627))
        self.uiphaTab.setObjectName(_fromUtf8("uiphaTab"))
        self.label_11 = QtGui.QLabel(self.uiphaTab)
        self.label_11.setGeometry(QtCore.QRect(230, 260, 91, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.toolBox.addItem(self.uiphaTab, _fromUtf8(""))
        self.uipacTab = QtGui.QWidget()
        self.uipacTab.setEnabled(False)
        self.uipacTab.setObjectName(_fromUtf8("uipacTab"))
        self.label_12 = QtGui.QLabel(self.uipacTab)
        self.label_12.setGeometry(QtCore.QRect(220, 260, 91, 17))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.toolBox.addItem(self.uipacTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.toolBox)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem25)
        self.pushButton_3 = QtGui.QPushButton(self.tab)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_10.addWidget(self.pushButton_3)
        spacerItem26 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem26)
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_10.addWidget(self.label_14)
        self.spinBox = QtGui.QSpinBox(self.tab)
        self.spinBox.setMinimum(-1)
        self.spinBox.setMaximum(8)
        self.spinBox.setProperty("value", -1)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout_10.addWidget(self.spinBox)
        spacerItem27 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem27)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.label_7 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setOpenExternalLinks(True)
        self.label_7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_advanced = QtGui.QWidget()
        self.tab_advanced.setObjectName(_fromUtf8("tab_advanced"))
        self.checkBox_6 = QtGui.QCheckBox(self.tab_advanced)
        self.checkBox_6.setGeometry(QtCore.QRect(30, 20, 86, 22))
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.tabWidget.addTab(self.tab_advanced, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.mplwindow = QtGui.QWidget(self.centralwidget)
        self.mplwindow.setMinimumSize(QtCore.QSize(400, 0))
        self.mplwindow.setObjectName(_fromUtf8("mplwindow"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.mplwindow)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.mplbox = QtGui.QVBoxLayout()
        self.mplbox.setContentsMargins(0, -1, -1, -1)
        self.mplbox.setObjectName(_fromUtf8("mplbox"))
        self.verticalLayout_9.addLayout(self.mplbox)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem28 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem28)
        self.checkBox = QtGui.QCheckBox(self.mplwindow)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_7.addWidget(self.checkBox)
        self.checkBox_2 = QtGui.QCheckBox(self.mplwindow)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.horizontalLayout_7.addWidget(self.checkBox_2)
        self.checkBox_3 = QtGui.QCheckBox(self.mplwindow)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.horizontalLayout_7.addWidget(self.checkBox_3)
        self.checkBox_4 = QtGui.QCheckBox(self.mplwindow)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.horizontalLayout_7.addWidget(self.checkBox_4)
        self.checkBox_5 = QtGui.QCheckBox(self.mplwindow)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.horizontalLayout_7.addWidget(self.checkBox_5)
        spacerItem29 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem29)
        self.label_15 = QtGui.QLabel(self.mplwindow)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_7.addWidget(self.label_15)
        self.visTo = QtGui.QSpinBox(self.mplwindow)
        self.visTo.setObjectName(_fromUtf8("visTo"))
        self.horizontalLayout_7.addWidget(self.visTo)
        spacerItem30 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem30)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.verticalLayout_9)
        self.horizontalLayout_2.addWidget(self.mplwindow)
        bpui.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(bpui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1310, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuOption = QtGui.QMenu(self.menubar)
        self.menuOption.setObjectName(_fromUtf8("menuOption"))
        self.menuMode = QtGui.QMenu(self.menubar)
        self.menuMode.setObjectName(_fromUtf8("menuMode"))
        self.menuDisplay = QtGui.QMenu(self.menubar)
        self.menuDisplay.setObjectName(_fromUtf8("menuDisplay"))
        bpui.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(bpui)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        bpui.setStatusBar(self.statusbar)
        self.actionAdvanced = QtGui.QAction(bpui)
        self.actionAdvanced.setObjectName(_fromUtf8("actionAdvanced"))
        self.actionDebugger = QtGui.QAction(bpui)
        self.actionDebugger.setObjectName(_fromUtf8("actionDebugger"))
        self.actionTab_settings = QtGui.QAction(bpui)
        self.actionTab_settings.setCheckable(True)
        self.actionTab_settings.setChecked(True)
        self.actionTab_settings.setObjectName(_fromUtf8("actionTab_settings"))
        self.menuMode.addAction(self.actionAdvanced)
        self.menuMode.addAction(self.actionDebugger)
        self.menuDisplay.addAction(self.actionTab_settings)
        self.menubar.addAction(self.menuOption.menuAction())
        self.menubar.addAction(self.menuDisplay.menuAction())
        self.menubar.addAction(self.menuMode.menuAction())

        self.retranslateUi(bpui)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(bpui)

    def retranslateUi(self, bpui):
        bpui.setWindowTitle(_translate("bpui", "brainpipe - Features", None))
        self.tabWidget.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Time Domain Analysis</span> (ERP...)</p></body></html>", None))
        self.uicd.setText(_translate("bpui", "Change current directory", None))
        self.label_26.setText(_translate("bpui", "List of files", None))
        self.label_27.setText(_translate("bpui", "List of variables inside the file", None))
        self.label_28.setText(_translate("bpui", "Variale to use for data", None))
        self.dataShape.setText(_translate("bpui", "       ", None))
        self.label_13.setText(_translate("bpui", "Sampling frequency", None))
        self.label_29.setText(_translate("bpui", "Name of the dataset", None))
        self.addNewData.setText(_translate("bpui", "Add dataset", None))
        self.datasetValid.setText(_translate("bpui", "             ", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("bpui", "Load", None))
        item = self.sumTable.horizontalHeaderItem(0)
        item.setText(_translate("bpui", "Name", None))
        item = self.sumTable.horizontalHeaderItem(1)
        item.setText(_translate("bpui", "Shape", None))
        item = self.sumTable.horizontalHeaderItem(2)
        item.setText(_translate("bpui", "sf", None))
        self.rmDataset.setText(_translate("bpui", "Remove", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("bpui", "Summarize", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("bpui", "Transform", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("bpui", "Data", None))
        self.label_19.setText(_translate("bpui", "ERP(supperposée à travers capteur ou un seul capteur) AVEC MOYENNAGE + FILTRAGE", None))
        self.label_20.setText(_translate("bpui", "rawdata (supperposée à travers capteur ou un seul capteur) SANS MOYENNAGE", None))
        self.label_23.setText(_translate("bpui", "Time Domain Analysis", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("bpui", "TDA", None))
        self.label_21.setText(_translate("bpui", "Plot pwelsch (par capteur)", None))
        self.label_22.setText(_translate("bpui", "(topoplot)", None))
        self.label_24.setText(_translate("bpui", "Frequency Domain Analysis", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("bpui", "FDA", None))
        self.label_16.setText(_translate("bpui", "TF moyénnées", None))
        self.label_17.setText(_translate("bpui", "TF essais par essais", None))
        self.label_18.setText(_translate("bpui", "Pour tout les essais, power dans une bande fce + temps", None))
        self.label_25.setText(_translate("bpui", "Time Frequency Analysis", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("bpui", "TFR", None))
        self.groupBox_3.setTitle(_translate("bpui", "Frequency bands", None))
        item = self.powTable.verticalHeaderItem(0)
        item.setText(_translate("bpui", "1", None))
        item = self.powTable.verticalHeaderItem(1)
        item.setText(_translate("bpui", "2", None))
        item = self.powTable.verticalHeaderItem(2)
        item.setText(_translate("bpui", "3", None))
        item = self.powTable.verticalHeaderItem(3)
        item.setText(_translate("bpui", "4", None))
        item = self.powTable.verticalHeaderItem(4)
        item.setText(_translate("bpui", "5", None))
        item = self.powTable.horizontalHeaderItem(0)
        item.setText(_translate("bpui", "Name", None))
        item = self.powTable.horizontalHeaderItem(1)
        item.setText(_translate("bpui", "From", None))
        item = self.powTable.horizontalHeaderItem(2)
        item.setText(_translate("bpui", "To", None))
        __sortingEnabled = self.powTable.isSortingEnabled()
        self.powTable.setSortingEnabled(False)
        item = self.powTable.item(0, 0)
        item.setText(_translate("bpui", "Delta", None))
        item = self.powTable.item(0, 1)
        item.setText(_translate("bpui", "2.0", None))
        item = self.powTable.item(0, 2)
        item.setText(_translate("bpui", "4.0", None))
        item = self.powTable.item(1, 0)
        item.setText(_translate("bpui", "Theta", None))
        item = self.powTable.item(1, 1)
        item.setText(_translate("bpui", "5.0", None))
        item = self.powTable.item(1, 2)
        item.setText(_translate("bpui", "7.0", None))
        item = self.powTable.item(2, 0)
        item.setText(_translate("bpui", "Alpha", None))
        item = self.powTable.item(2, 1)
        item.setText(_translate("bpui", "8.0", None))
        item = self.powTable.item(2, 2)
        item.setText(_translate("bpui", "13.0", None))
        item = self.powTable.item(3, 0)
        item.setText(_translate("bpui", "Beta", None))
        item = self.powTable.item(3, 1)
        item.setText(_translate("bpui", "13.0", None))
        item = self.powTable.item(3, 2)
        item.setText(_translate("bpui", "30.0", None))
        item = self.powTable.item(4, 0)
        item.setText(_translate("bpui", "Gamma", None))
        item = self.powTable.item(4, 1)
        item.setText(_translate("bpui", "30.0", None))
        item = self.powTable.item(4, 2)
        item.setText(_translate("bpui", "60.0", None))
        self.powTable.setSortingEnabled(__sortingEnabled)
        self.powFceAdd.setText(_translate("bpui", "Add", None))
        self.powFceRm.setText(_translate("bpui", "Remove", None))
        self.groupBox_4.setTitle(_translate("bpui", "Other settings", None))
        self.powBsl.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Normalize the power using a baseline</span></p></body></html>", None))
        self.powBsl.setText(_translate("bpui", "Baseline", None))
        self.label_8.setText(_translate("bpui", "From", None))
        self.powBslFrom.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Define where the baseline start</span> (in SAMPLE)</p></body></html>", None))
        self.label_9.setText(_translate("bpui", "To", None))
        self.powBslTo.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Define where the baseline finish</span> (in SAMPLE)</p></body></html>", None))
        self.powAdv.setText(_translate("bpui", "Advanced", None))
        self.groupBox_5.setTitle(_translate("bpui", "Your configuration", None))
        self.powResume.setText(_translate("bpui", "resume", None))
        self.powCycle.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Nombre de cycle (pour l\'option de filtrage firls)</span></p><p><span style=\" text-decoration: underline;\">Effet :</span> Nombre de cycles à considérer pour calculer l\'ordre du filtre. Pour des basses fréquences (delta / theta / alpha / beta), on préfèrera des valeurs proches de 3. Pour des hautes fréquences (&gt;= 60), un plus grand nombre de cycles peut améliorer l\'estimation de puissance. 6 cycles est une bonne valeur (cf. Bahramisharif et al., 2013 )</p></body></html>", None))
        self.label_3.setText(_translate("bpui", "Order", None))
        self.powBut.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Type de filtre pour extraire les informations spectrales.</span></p><p><span style=\" text-decoration: underline;\">- butter:</span> filtre Butterworth (bon compromis entre vitesse et précision mais introduit un décalage)</p><p><span style=\" text-decoration: underline;\">- bessel: </span> filtre de bessel (introduit un décalage)</p><p><span style=\" text-decoration: underline;\">- fir1:</span> Finite Response Filter - Least Square (cf. Delorme and Makeig, 2004) - filtre très précis, qui conserve la phase mais deux fois plus lent</p></body></html>", None))
        self.powBut.setWhatsThis(_translate("bpui", "<html><head/><body><p><br/></p></body></html>", None))
        self.powBut.setItemText(0, _translate("bpui", "butter", None))
        self.powBut.setItemText(1, _translate("bpui", "bessel", None))
        self.powBut.setItemText(2, _translate("bpui", "fir1", None))
        self.label_4.setText(_translate("bpui", "Cycle", None))
        self.label_2.setText(_translate("bpui", "Transformation", None))
        self.powTrans.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Méthode de calcul de puissance. Ces méthodes permettent de passer un signal du domaine réel au domaine complexe. Ces deux méthodes offrent des résultats comparables</span></p><p><span style=\" text-decoration: underline;\">- Wavelet :</span> transformée en ondelettes (voir Thomas pour plus de détail)</p><p><span style=\" text-decoration: underline;\">- Hilbert :</span> la transformée d\'Hilbert permet de décomposer un signal en phase / amplitude</p></body></html>", None))
        self.powTrans.setItemText(0, _translate("bpui", "wavelet", None))
        self.powTrans.setItemText(1, _translate("bpui", "hilbert1", None))
        self.powOrder.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Ordre du filtre Butterworth ou Bessel </span>(pas d\'effet sur firls)</p><p><span style=\" text-decoration: underline;\">Effet:</span> Filtrage plus ou moins efficace mais peut engendrer des distorsions (ou artefact) dans le signal. De plus, un ordre trop grand peut considérablement augmenter le temps de calcul</p></body></html>", None))
        self.label.setText(_translate("bpui", "Filter", None))
        self.label_5.setText(_translate("bpui", "Detrend", None))
        self.powDetrend.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Permet d\'applique un </span><span style=\" font-weight:600; font-style:italic;\">detrending</span><span style=\" font-weight:600;\"> au signal</span></p></body></html>", None))
        self.label_6.setText(_translate("bpui", "Width", None))
        self.powWidth.setToolTip(_translate("bpui", "<html><head/><body><p><span style=\" font-weight:600;\">Taille de l\'ondelette</span></p></body></html>", None))
        self.label_10.setText(_translate("bpui", "Normalization", None))
        self.powNorm.setToolTip(_translate("bpui", "<html><head/><body><p>Définit le type de normalisation pour corriger la puissance par la baseline</p><p>        0 : Pas de normalisation</p><p>        1 : Soustraction de la moyenne de la baseline</p><p>        2 : Division par la moyenne de la baseline</p><p>        3 : Soustraction puis division par la moyenne de la baseline</p><p>        4 : Soustraction de la moyenne de la baseline puis division par la déviation de la baseline (Z-score)</p></body></html>", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.uipowTab), _translate("bpui", "Power", None))
        self.label_11.setText(_translate("bpui", "Coming soon", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.uiphaTab), _translate("bpui", "Phase", None))
        self.label_12.setText(_translate("bpui", "Coming soon", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.uipacTab), _translate("bpui", "Phase-Amplitude Coupling", None))
        self.pushButton_3.setText(_translate("bpui", "Run", None))
        self.label_14.setText(_translate("bpui", "n_jobs", None))
        self.label_7.setText(_translate("bpui", "<html><head/><body><p><span style=\" text-decoration: underline;\">Contact</span>: <span style=\" color:#0000ff;\">e.combrisson@gmail.com</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("bpui", "Features", None))
        self.checkBox_6.setText(_translate("bpui", "Activate", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_advanced), _translate("bpui", "Advanced", None))
        self.checkBox.setText(_translate("bpui", "Time series", None))
        self.checkBox_2.setText(_translate("bpui", "Power", None))
        self.checkBox_3.setText(_translate("bpui", "Phase", None))
        self.checkBox_4.setText(_translate("bpui", "PAC", None))
        self.checkBox_5.setText(_translate("bpui", "TF", None))
        self.label_15.setText(_translate("bpui", "Channel: ", None))
        self.menuOption.setTitle(_translate("bpui", "Option", None))
        self.menuMode.setTitle(_translate("bpui", "Mode", None))
        self.menuDisplay.setTitle(_translate("bpui", "Display", None))
        self.actionAdvanced.setText(_translate("bpui", "Advanced", None))
        self.actionDebugger.setText(_translate("bpui", "Debugger", None))
        self.actionTab_settings.setText(_translate("bpui", "Tab settings", None))
        self.actionTab_settings.setShortcut(_translate("bpui", "Ctrl+T", None))

